sudo: required
group: deprecated-2017Q2

services:
  - docker

install:
  - docker build --tag bodsch/docker-icinga2 .
  - docker run --detach --name icinga2 bodsch/docker-icinga2

script:
  - docker ps | grep -q icinga2

