sudo: required

group: edge

services:
  - docker

install:
  - travis_retry docker build --tag bodsch/docker-icinga2 .
  - docker run --detach --name icinga2 bodsch/docker-icinga2

script:
  - docker-compose --file docker-compose_example.yml up --build -d
  - tests/test.sh
  - docker-compose --file docker-compose_example.yml kill
  - docker-compose --file docker-compose_example.yml down

after_success:
  - |
    [ "${TRAVIS_BRANCH}" == "master" ] && curl \
      --request POST \
      --header "Content-Type: application/json"  \
      --data '{"source_type":"Branch","source_name":"master"}' \
      https://registry.hub.docker.com/u/bodsch/docker-icinga2/trigger/${DOCKER_HUB_TOKEN}/
