# sudo: required

group: edge

services:
  - docker

env:
  global:
    - ICINGA2_VERSION=${ICINGA2_VERSION:-2.9.1}
    - BUILD_DATE=$(date +"%Y-%m-%d")

jobs:
  include:

    - stage: build debian
      script:
        - make
        - docker-compose --file docker-compose.yml up --build -d
        - sleep 5m
        - tests/test.sh
        - docker-compose --file docker-compose.yml kill
        - docker-compose --file docker-compose.yml down

#    - stage: build debian and push image
#      script:
#        - make debian
#        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
#        - docker tag ${DOCKER_USERNAME}/docker-icinga2:debian-${ICINGA2_VERSION}           ${DOCKER_USERNAME}/docker-icinga2:debian-latest
#        - docker tag ${DOCKER_USERNAME}/docker-icinga2:debian-master-${ICINGA2_VERSION}    ${DOCKER_USERNAME}/docker-icinga2:debian-master-latest
#        - docker tag ${DOCKER_USERNAME}/docker-icinga2:debian-satellite-${ICINGA2_VERSION} ${DOCKER_USERNAME}/docker-icinga2:debian-satellite-latest
#        - docker push ${DOCKER_USERNAME}/docker-icinga2:debian-latest
#        - docker push ${DOCKER_USERNAME}/docker-icinga2:debian-master-latest
#        - docker push ${DOCKER_USERNAME}/docker-icinga2:debian-satellite-latest
#        - docker logout

#    - stage: build alpine
#      script:
#        - make alpine
#        - make compose-alpine
#        - docker-compose --file docker-compose_alpine.yml up --build -d
#        - sleep 4m
#        - tests/test.sh
#        - docker-compose --file docker-compose_alpine.yml kill
#        - docker-compose --file docker-compose_alpine.yml down

#    - stage: build alpine and push image
#      script:
#        - make alpine
#        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
#        - docker tag ${DOCKER_USERNAME}/docker-icinga2:alpine-${ICINGA2_VERSION}           ${DOCKER_USERNAME}/docker-icinga2:alpine-latest
#        - docker tag ${DOCKER_USERNAME}/docker-icinga2:alpine-master-${ICINGA2_VERSION}    ${DOCKER_USERNAME}/docker-icinga2:alpine-master-latest
#        - docker tag ${DOCKER_USERNAME}/docker-icinga2:alpine-satellite-${ICINGA2_VERSION} ${DOCKER_USERNAME}/docker-icinga2:alpine-satellite-latest
#        - docker push ${DOCKER_USERNAME}/docker-icinga2:alpine-latest
#        - docker push ${DOCKER_USERNAME}/docker-icinga2:alpine-master-latest
#        - docker push ${DOCKER_USERNAME}/docker-icinga2:alpine-satellite-latest
#        - docker logout
