# sudo: required

group: edge

services:
  - docker

env:
  global:
    - ICINGA2_VERSION=${ICINGA2_VERSION:-2.8.2}
    - ICINGA2_VCS_REF=dev
    - BUILD_DATE=$(date +"%Y-%m-%d")

jobs:
  include:
    - stage: build docker image
      script:
        - make build
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - docker push ${DOCKER_USERNAME}/docker-icinga2:${ICINGA2_VERSION}-${ICINGA2_VCS_REF}
    - stage: test images
      script:
        - docker-compose --file docker-compose_example.yml up --build -d
        - tests/test.sh
        - docker-compose --file docker-compose_example.yml kill
        - docker-compose --file docker-compose_example.yml down
    - stage: push to docker hub
      script:
        - make build
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
        - make publish
