# sudo: required

group: edge

services:
  - docker

env:
  global:
    - ICINGA2_VERSION=${ICINGA2_VERSION:-2.9.1}
    - BUILD_DATE=$(date +"%Y-%m-%d")

jobs:
  include:

    - stage: build and test
      script:
        - make
        - docker-compose build
        - docker-compose up -d
        - sleep 6m
        - tests/test.sh
        - docker-compose kill
        - docker-compose down

    - stage: build and push image
      script:
        - make
        - docker tag ${DOCKER_USERNAME}/docker-icinga2:${ICINGA2_VERSION}-master    ${DOCKER_USERNAME}/docker-icinga2:latest-master
        - docker tag ${DOCKER_USERNAME}/docker-icinga2:${ICINGA2_VERSION}-satellite ${DOCKER_USERNAME}/docker-icinga2:latest-satellite
        - docker login --username "${DOCKER_USERNAME}" --password "${DOCKER_PASSWORD}"
        - docker push ${DOCKER_USERNAME}/docker-icinga2:${ICINGA2_VERSION}-master
        - docker push ${DOCKER_USERNAME}/docker-icinga2:${ICINGA2_VERSION}-satellite
        - docker push ${DOCKER_USERNAME}/docker-icinga2:latest-master
        - docker push ${DOCKER_USERNAME}/docker-icinga2:latest-satellite
        - docker logout
